name: Jekyll

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Ruby
      uses: ruby/setup-ruby@v1

    - name: Install gems
      run: bundle install

    - name: Build site
      run: bin/jekyll
